import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { Provider } from '@/components/providers'
import { DefaultLayout } from '@/components/template/DefaultLayout'
import { Suspense } from 'react'
import Loading from './loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Eventmakers NID',
  description: 'Generated by create next app',
}

// EVERY PAGE WRAPPED BY THIS LAYOUT, RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <DefaultLayout>
            <Suspense fallback={<Loading/>}>{children}</Suspense>
          </DefaultLayout>
        </Provider>
      </body>
    </html>
  )
}
